---
# See the available options: https://tdt-documentation.london.cloudapps.digital/configure_project/global_configuration/#configure-your-documentation-site

host: https://user-guide.analytical-platform.service.justice.gov.uk
show_govuk_logo: false
service_name: Analytical Platform User Guide
service_link: /
header_links:
  Control Panel: https://controlpanel.services.analytical-platform.service.justice.gov.uk/
  Status: https://status.analytical-platform.service.justice.gov.uk/posts/dashboard
  Support: https://github.com/ministryofjustice/data-platform-support/issues/new?template=analytical-platform-support.yml
footer_links:
  Ask us a question on Slack: https://moj.enterprise.slack.com/archives/C06TFT94JTC
  Raise an issue on GitHub: https://github.com/ministryofjustice/data-platform-support/issues/new?template=analytical-platform-support.yml
enable_search: true
collapsible_nav: true
max_toc_heading_level: 3
prevent_indexing: true
show_contribution_banner: true
github_repo: ministryofjustice/analytical-platform-user-guide
github_branch: main
full_service_name: Analytical Platform User Guide
show_expiry: true
show_review_banner: true
