---
name: Build and Publish

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: docker.io/ministryofjustice/tech-docs-github-pages-publisher@sha256:26b720c51b12f13b91d35b4447acbb21f437cfd94e36e1581ea631955ea616ba # v3.0.2
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        id: build
        run: |
          /scripts/deploy.sh

      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
          overwrite: true

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.configure_pages.outputs.base_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Configure Pages
        id: configure_pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0

      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@87c3283f01cd6fe19a0ab93a23b2f6fcba5a8e42 # v4.0.3
